name: CI
on:
  workflow_call:
    inputs:
      deployment-region:
        required: true
        type: string  
jobs:
  azure_adf_precopy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment-region }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  # azure_adf_login:
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.deployment-region }}
  #   needs: azure_adf_precopy
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run a one-line script
  #       run: echo Hello, world!
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.

  # azure_adf_stop_triggers:
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.deployment-region }}
  #   needs: azure_adf_login    
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run a one-line script
  #       run: echo Hello, world!
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.

  # azure_adf_dry_run:
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.deployment-region }}
  #   needs: azure_adf_stop_triggers    
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run a one-line script
  #       run: echo Hello, world!
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.

  # azure_adf_arm_update:
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.deployment-region }}
  #   needs: azure_adf_dry_run    
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run a one-line script
  #       run: echo Hello, world!
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.          

  # azue_adf_start_triggers:
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.deployment-region }}
  #   needs: azure_adf_arm_update    
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run a one-line script
  #       run: echo Hello, world!
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.   

  # azure_adf_post_validation:
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.deployment-region }}
  #   needs: azue_adf_start_triggers    
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run a one-line script
  #       run: echo Hello, world!
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.   

  azure_adf_logout:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment-region }}
    needs: azure_adf_precopy    
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.             
