name: CI
on:
  workflow_call:
jobs:
  azure_adf_precopy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  azure_adf_login:
    runs-on: ubuntu-latest
    needs: azure_adf_precopy
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  azure_adf_stop_triggers:
    runs-on: ubuntu-latest
    needs: azure_adf_login    
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  azure_adf_dry_run:
    runs-on: ubuntu-latest
    needs: azure_adf_stop_triggers    
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  azure_adf_arm_update:
    runs-on: ubuntu-latest
    needs: azure_adf_dry_run    
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.          

  azue_adf_start_triggers:
    runs-on: ubuntu-latest
    needs: azure_adf_arm_update    
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.   

  azure_adf_post_validation:
    runs-on: ubuntu-latest
    needs: azue_adf_start_triggers    
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.   

  azure_adf_logout:
    runs-on: ubuntu-latest
    needs: azure_adf_post_validation    
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.             
